### ISSUE TITLE
Dark mode settings

### ISSUE THREAD

**Issue by deepu2** [cylonid/NativeAlphaForAndroid#27] opened 2021-07-21 08:28 UTC
All shortcuts currently open with dark mode and some don't support them at all. A dark mode switch for web app would be a great addition since there is no way to override it now.

**Comment by cylonid** [comment] 2021-07-22 19:41
Thanks for the hint. In fact, you can turn this behaviour off but you have to disable the dark mode also for the app UI. Currently, the WebView takes over the dark mode setting of Native Alpha itself. This was unintended and will be fixed soon.

**Comment by cylonid** [comment] 2021-07-24 17:08
Fixed with v1.01

**Closed by cylonid** 2021-07-24 17:08 UTC

**Comment by Shuunen** [comment] 2021-07-30 08:55
Hi there 😄 firstly, thanks @cylonid the app is great 

I can't mange to have the dark mode even with `v1.0.1`

I made a test page here to detect dark theme behaviour : https://codepen.io/Shuunen/pen/zYwjNJv

If I open this url on my android browser with dark theme enabled I see this :

![image](https://user-images.githubusercontent.com/439158/127627782-cdab1879-3cfe-4bdd-a404-9fdf6058b753.png)

But if I create a webview with Alpha (even after setting UI to `system`, `light` or `dark`) I still see : 

![image](https://user-images.githubusercontent.com/439158/127627971-eab8f194-20a5-4875-9b90-fde8a0d537fb.png)

**Comment by cylonid** [comment] 2021-07-30 09:20
Hi @Shuunen,
I think you misunderstood this issue: The problem was that the Dark Mode setting was forced unconditionally on all Web Apps in v1.00. This is now fixed and all Web Apps are again rendered with light/standard mode. There is no working Dark Mode for the web pages in Native Alpha yet, this was a bug/unfinished feature. Dark Mode is currently only available for the app UI, so your test result is the expected behaviour.

**Comment by Shuunen** [comment] 2021-07-30 13:36
Ow ok, so I suppose I can downgrade to `v1.00` to have dark mode ?

**Comment by cylonid** [comment] 2021-07-30 15:44
If Dark Mode is that important to you and you don't care about the limitations, feel free to downgrade.
